name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  IMAGE_BASE_NAME: my-django-app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Looking for files
      run: ls -lh
    - name: Build the Docker image
      run: docker build . -t $IMAGE_BASE_NAME:$(date +%s)
