name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  IMAGE_BASE_NAME: my-django-app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Crate tag for docker image
      run: echo "IMAGE_BASE_NAME=${{ secrets.DOCKERHUB_USERNAME}}/my-django-app:$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . -t $IMAGE_BASE_NAME

    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pushing image to dockerhub
      run: |
        docker push $IMAGE_BASE_NAME